### ISSUE TITLE
那篇文章里的正则有些错误

### ISSUE THREAD

**Issue by Alex1990** [coolxuefeng/regTools#1]
- 邮政编码：河北省的市以`0`开头的，幸好我来自河北省；
- 身份证号：最后一位可能为字母`X`的，也要注意不应该区分大小写；
- 电话号码：区号为 4 位的市也有可能电话号码是 8 位，顺便用英文`tel`更合适吧，而且可能考虑分机号；
- 双字节字符：Unicode 编码是可变长的，中文就是一个汉字三个字节，即使计算字符串长度，一个非ASCII 字符算 2，ASCII 算 1 也是不严谨的，这里主要是视觉上一个汉字大概相当于两个英文字母的宽度。[validator.js](https://github.com/chriso/validator.js) 里面用得是 `fullWidth`/`halfWidth`，代码是：
  
  ``` js
  var fullWidth = /[^\u0020-\u007E\uFF61-\uFF9F\uFFA0-\uFFDC\uFFE8-\uFFEE0-9a-zA-Z]/;
  var halfWidth = /[\u0020-\u007E\uFF61-\uFF9F\uFFA0-\uFFDC\uFFE8-\uFFEE0-9a-zA-Z]/;
  ```
- 浮点数：是否包括 `-.1`，`-1.2e-2`之类呢？

**Comment by Alex1990** [comment]
那篇文章转载者甚多，我百度到的几乎和那片文章内容差不多，而没有几个人修正下错误，我只是顺便看到你写的这个了，就告诉你一下。

**Comment by coolxuefeng** [comment]
- 邮政编码，根据百度百科词条修改了正则。
- 身份证，已修正。
- 电话号码，删除，国内应该用不上了。
- 双字节字符，已修正。
- 浮点数，允许省略整数部分；暂不支持科学记数法，科学记数法与一般计数法的数字差别比较大。
- 顺便修正了一些其他错误。

这个项目其实是我学完一个正则表达式的课程之后用来练手用的。如果你还有其他建议，比如新增一些检查项，如何让它更友好之类的。多谢😁

**Comment by Alex1990** [comment]
没建议了，我现在正在学习这方面

**Comment by coolxuefeng** [comment]
我看的是这个课程，或许你用得上  http://www.imooc.com/learn/350
